import re
import timeit
img_id = "33bf7935-1c34-4d6a-94f5-f675319d6764"

captions ="[Image caption]: Here is a summary of the description:\
The cake is a light blue and white cake with a picture of a K-pop group on top, decorated with blue and white balls, stars, and a banner that says ""BABYMONSTER"". It's on a white plate or board, with a gray background, and features a number 10, suggesting it's a birthday cake for someone turning 10."

markdown = f"# Memahami Asam Lambung (Stomach Acid)\
## 1. Pendahuluan\
Asam lambung, atau yang dikenal dalam istilah medis sebagai asam hidroklorik, adalah cairan yang diproduksi oleh kelenjar di lambung. Cairan ini memiliki peran yang sangat penting dalam proses pencernaan makanan, terutama dalam membantu memecah makanan dan membunuh bakteri yang mungkin masuk ke dalam sistem pencernaan. Asam lambung tidak hanya berfungsi sebagai agen pencernaan, tetapi juga berperan dalam mengaktifkan enzim pencernaan dan memfasilitasi penyerapan nutrisi. Memahami asam lambung dan dampaknya terhadap kesehatan sangatlah penting, karena ketidakseimbangan dalam produksi asam lambung dapat menyebabkan berbagai masalah kesehatan, termasuk gangguan pencernaan, refluks asam, dan bahkan komplikasi yang lebih serius seperti esofagitis atau kanker esofagus. Dalam artikel ini, kita akan membahas secara mendalam mengenai penyebab, gejala, diagnosis, pengobatan, serta rekomendasi diet yang berkaitan dengan asam lambung. Dengan pemahaman yang lebih baik tentang asam lambung, kita dapat mengambil langkah-langkah yang tepat untuk menjaga kesehatan pencernaan kita.\
## 2. Penyebab Asam Lambung\
Penyebab utama dari masalah asam lambung dapat bervariasi, namun beberapa faktor yang paling umum meliputi pola makan yang tidak sehat, gaya hidup yang kurang baik, dan kondisi medis tertentu. Diet yang tinggi lemak, makanan pedas, serta konsumsi alkohol dan kafein dapat meningkatkan produksi asam lambung. Misalnya, makanan yang digoreng dan berlemak dapat memperlambat proses pencernaan, sehingga lambung memproduksi lebih banyak asam untuk memecah makanan tersebut. Selain itu, kebiasaan merokok juga dapat berkontribusi terhadap peningkatan asam lambung, karena nikotin dapat merelaksasi otot-otot di bagian bawah kerongkongan, yang seharusnya mencegah asam lambung naik kembali. Dari segi gaya hidup, stres dan kurang tidur dapat mempengaruhi keseimbangan asam lambung dalam tubuh. Stres dapat memicu produksi asam lambung yang berlebihan, sementara kurang tidur dapat mengganggu proses pemulihan tubuh. Beberapa kondisi medis, seperti hernia hiatal, gastritis, dan penyakit refluks gastroesofagus (GERD), juga dapat menyebabkan peningkatan produksi asam lambung. Memahami penyebab-penyebab ini sangat penting untuk mencegah dan mengelola masalah yang berkaitan dengan asam lambung. Dengan mengidentifikasi faktor-faktor pemicu, individu dapat mengambil langkah-langkah proaktif untuk mengurangi risiko masalah asam lambung.\
## 3. Gejala Asam Lambung\
Gejala yang paling umum terkait dengan masalah asam lambung termasuk nyeri ulu hati, regurgitasi, dan kesulitan menelan. Nyeri ulu hati biasanya dirasakan sebagai sensasi terbakar di dada, yang dapat menyebar ke leher dan tenggorokan. Sensasi ini sering kali muncul setelah makan atau saat berbaring, dan dapat sangat mengganggu aktivitas sehari-hari. Regurgitasi adalah kondisi di mana asam lambung naik kembali ke kerongkongan, menyebabkan rasa asam atau pahit di mulut. Beberapa orang mungkin juga mengalami kesulitan menelan, yang dikenal sebagai disfagia, yang dapat disebabkan oleh peradangan pada kerongkongan akibat paparan asam lambung. Selain itu, beberapa orang mungkin mengalami gejala lain seperti mual, batuk kronis, dan suara serak. Batuk kronis dapat terjadi akibat iritasi pada tenggorokan akibat asam lambung yang naik, sementara suara serak dapat disebabkan oleh peradangan pada pita suara. Penting untuk mengenali gejala-gejala ini, karena jika tidak ditangani, dapat menyebabkan komplikasi yang lebih serius, seperti kerusakan pada esofagus atau bahkan kanker esofagus. Oleh karena itu, penting bagi individu untuk memperhatikan tanda-tanda peringatan dan mencari bantuan medis jika gejala berlanjut atau memburuk.\
## 4. Diagnosis dan Pengobatan\
Diagnosis masalah asam lambung biasanya dilakukan melalui pemeriksaan fisik dan riwayat medis pasien. Dokter mungkin juga merekomendasikan tes tambahan, seperti endoskopi, untuk melihat kondisi lambung dan kerongkongan secara langsung. Endoskopi adalah prosedur di mana dokter menggunakan alat yang disebut endoskop untuk melihat bagian dalam saluran pencernaan. Selain itu, tes pH esofagus dapat dilakukan untuk mengukur tingkat keasaman di kerongkongan. Pengobatan untuk masalah asam lambung dapat bervariasi tergantung pada penyebab dan tingkat keparahan gejala. Pengobatan umum termasuk penggunaan obat-obatan seperti antasida, inhibitor pompa proton, dan antagonis reseptor H2. Antasida bekerja dengan menetralkan asam lambung yang sudah ada, sementara inhibitor pompa proton dan antagonis reseptor H2 mengurangi produksi asam lambung. Selain itu, perubahan gaya hidup, seperti menghindari makanan pemicu, mengurangi berat badan, dan berhenti merokok, juga sangat dianjurkan untuk mengelola gejala asam lambung. Mengadopsi kebiasaan makan yang sehat dan menghindari makanan yang dapat memicu gejala juga merupakan langkah penting dalam pengobatan masalah asam lambung. Dengan pendekatan yang tepat, banyak individu dapat menemukan perbaikan signifikan dalam gejala mereka dan meningkatkan kualitas hidup mereka.\
## 5. Rekomendasi Diet\
Diet memainkan peran yang sangat penting dalam mengelola masalah asam lambung. Beberapa makanan yang sebaiknya dihindari termasuk makanan pedas, makanan berlemak, cokelat, kafein, dan minuman berkarbonasi. Makanan pedas dapat merangsang produksi asam lambung, sementara makanan berlemak dapat memperlambat proses pencernaan. Cokelat dan kafein juga dapat merelaksasi otot-otot di bagian bawah kerongkongan, yang dapat menyebabkan refluks asam. Sebaliknya, makanan yang dapat membantu mengurangi gejala asam lambung meliputi sayuran hijau, oatmeal, pisang, dan yogurt. Sayuran hijau seperti brokoli dan bayam kaya akan serat dan dapat membantu menetralkan asam lambung. Oatmeal adalah sumber karbohidrat kompleks yang baik dan dapat membantu menyerap asam lambung. Pisang memiliki sifat antasid alami, sementara yogurt mengandung probiotik yang dapat mendukung kesehatan pencernaan. Mengonsumsi makanan dalam porsi kecil dan sering juga dapat membantu mengurangi tekanan pada lambung dan mencegah peningkatan produksi asam lambung. Selain itu, penting untuk menjaga hidrasi yang cukup dengan mengonsumsi air putih yang cukup sepanjang hari. Menghindari makan terlalu dekat dengan waktu tidur juga dapat membantu mencegah gejala refluks asam. Dengan mengikuti rekomendasi diet yang tepat, individu dapat mengelola gejala asam lambung dengan lebih efektif dan meningkatkan kesehatan pencernaan mereka secara keseluruhan. ![image-{img_id}]\
    \n Minimal nyenggol anak tetangga ini boss. ![image-33bf7935-1c34-4d6a-94f5-f675320a6744]"


start_time = timeit.default_timer()
pattern = rf"!\[image-{img_id}\]"
str_output = re.sub(pattern, captions, markdown)
end_time = timeit.default_timer()
print(str_output)
print({end_time - start_time})